apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: acc-k8s-device-plugin-daemonset
  namespace: kube-system
spec:
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: acc-k8s-device-plugin-ds
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - image: kaistncl/accelerator-k8s:latest
        name: acc-k8s-device-plugin-ctr
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: acc-k8s
            mountPath: /etc/accelerator-docker/
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: acc-k8s
          hostPath:
            path: /etc/accelerator-docker