apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: acc-k8s
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: acc-k8s-ds
    spec:
      priorityClassName: "system-node-critical"
      containers:
      - image: kaistncl/accelerator-k8s:latest
        name: acc-k8s-ctr
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: acc-k8s
            mountPath: /etc/accelerator-docker/
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: acc-k8s
          hostPath:
            path: /etc/accelerator-docker
