// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device_proto/device.proto

package device

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Device_Status int32

const (
	Device_IDLE Device_Status = 0
	Device_USED Device_Status = 1
)

var Device_Status_name = map[int32]string{
	0: "IDLE",
	1: "USED",
}

var Device_Status_value = map[string]int32{
	"IDLE": 0,
	"USED": 1,
}

func (x Device_Status) Enum() *Device_Status {
	p := new(Device_Status)
	*p = x
	return p
}

func (x Device_Status) String() string {
	return proto.EnumName(Device_Status_name, int32(x))
}

func (x *Device_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_Status_value, data, "Device_Status")
	if err != nil {
		return err
	}
	*x = Device_Status(value)
	return nil
}

func (Device_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3d2cb7e7d325adae, []int{2, 0}
}

type EnvEntry struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,req,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvEntry) Reset()         { *m = EnvEntry{} }
func (m *EnvEntry) String() string { return proto.CompactTextString(m) }
func (*EnvEntry) ProtoMessage()    {}
func (*EnvEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d2cb7e7d325adae, []int{0}
}

func (m *EnvEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvEntry.Unmarshal(m, b)
}
func (m *EnvEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvEntry.Marshal(b, m, deterministic)
}
func (m *EnvEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvEntry.Merge(m, src)
}
func (m *EnvEntry) XXX_Size() int {
	return xxx_messageInfo_EnvEntry.Size(m)
}
func (m *EnvEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvEntry.DiscardUnknown(m)
}

var xxx_messageInfo_EnvEntry proto.InternalMessageInfo

func (m *EnvEntry) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *EnvEntry) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type FileEntry struct {
	Src                  *string  `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	Dst                  *string  `protobuf:"bytes,2,req,name=dst" json:"dst,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileEntry) Reset()         { *m = FileEntry{} }
func (m *FileEntry) String() string { return proto.CompactTextString(m) }
func (*FileEntry) ProtoMessage()    {}
func (*FileEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d2cb7e7d325adae, []int{1}
}

func (m *FileEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileEntry.Unmarshal(m, b)
}
func (m *FileEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileEntry.Marshal(b, m, deterministic)
}
func (m *FileEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileEntry.Merge(m, src)
}
func (m *FileEntry) XXX_Size() int {
	return xxx_messageInfo_FileEntry.Size(m)
}
func (m *FileEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FileEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FileEntry proto.InternalMessageInfo

func (m *FileEntry) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *FileEntry) GetDst() string {
	if m != nil && m.Dst != nil {
		return *m.Dst
	}
	return ""
}

type Device struct {
	Name                 *string        `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Pci                  *string        `protobuf:"bytes,2,opt,name=pci" json:"pci,omitempty"`
	DeviceDriver         []string       `protobuf:"bytes,3,rep,name=device_driver,json=deviceDriver" json:"device_driver,omitempty"`
	Library              []string       `protobuf:"bytes,4,rep,name=library" json:"library,omitempty"`
	File                 []*FileEntry   `protobuf:"bytes,5,rep,name=file" json:"file,omitempty"`
	Env                  []*EnvEntry    `protobuf:"bytes,6,rep,name=env" json:"env,omitempty"`
	Type                 *string        `protobuf:"bytes,7,opt,name=type" json:"type,omitempty"`
	Status               *Device_Status `protobuf:"varint,8,opt,name=status,enum=device.Device_Status" json:"status,omitempty"`
	Pid                  *int32         `protobuf:"varint,9,opt,name=pid" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d2cb7e7d325adae, []int{2}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Device) GetPci() string {
	if m != nil && m.Pci != nil {
		return *m.Pci
	}
	return ""
}

func (m *Device) GetDeviceDriver() []string {
	if m != nil {
		return m.DeviceDriver
	}
	return nil
}

func (m *Device) GetLibrary() []string {
	if m != nil {
		return m.Library
	}
	return nil
}

func (m *Device) GetFile() []*FileEntry {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Device) GetEnv() []*EnvEntry {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Device) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Device) GetStatus() Device_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Device_IDLE
}

func (m *Device) GetPid() int32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

type DeviceList struct {
	Devices              []*Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeviceList) Reset()         { *m = DeviceList{} }
func (m *DeviceList) String() string { return proto.CompactTextString(m) }
func (*DeviceList) ProtoMessage()    {}
func (*DeviceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d2cb7e7d325adae, []int{3}
}

func (m *DeviceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceList.Unmarshal(m, b)
}
func (m *DeviceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceList.Marshal(b, m, deterministic)
}
func (m *DeviceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceList.Merge(m, src)
}
func (m *DeviceList) XXX_Size() int {
	return xxx_messageInfo_DeviceList.Size(m)
}
func (m *DeviceList) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceList.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceList proto.InternalMessageInfo

func (m *DeviceList) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

func init() {
	proto.RegisterEnum("device.Device_Status", Device_Status_name, Device_Status_value)
	proto.RegisterType((*EnvEntry)(nil), "device.env_entry")
	proto.RegisterType((*FileEntry)(nil), "device.file_entry")
	proto.RegisterType((*Device)(nil), "device.device")
	proto.RegisterType((*DeviceList)(nil), "device.device_list")
}

func init() { proto.RegisterFile("device_proto/device.proto", fileDescriptor_3d2cb7e7d325adae) }

var fileDescriptor_3d2cb7e7d325adae = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0xcb, 0x4a, 0xf3, 0x40,
	0x14, 0xfe, 0x73, 0x69, 0xda, 0x9c, 0xfe, 0x96, 0x7a, 0x40, 0x38, 0x82, 0x8b, 0x90, 0x82, 0x64,
	0x63, 0x2b, 0xdd, 0xf8, 0x02, 0xe9, 0x42, 0x70, 0x35, 0xc5, 0x75, 0x89, 0xc9, 0x08, 0x83, 0x31,
	0x0d, 0x33, 0x63, 0x20, 0x0f, 0xe5, 0x3b, 0xca, 0x4c, 0x66, 0x2c, 0xae, 0xf2, 0x5d, 0x99, 0xef,
	0x04, 0x6e, 0x1b, 0x3e, 0x88, 0x9a, 0x9f, 0x7a, 0x79, 0xd6, 0xe7, 0xdd, 0x44, 0xb6, 0x96, 0x60,
	0x32, 0xb1, 0x7c, 0x07, 0x29, 0xef, 0x86, 0x13, 0xef, 0xb4, 0x1c, 0x71, 0x0d, 0xd1, 0x07, 0x1f,
	0x29, 0xc8, 0xc2, 0x22, 0x65, 0x06, 0x1a, 0x65, 0xa8, 0x5a, 0x0a, 0x27, 0x65, 0xa8, 0xda, 0xfc,
	0x11, 0xe0, 0x5d, 0xb4, 0xfc, 0xd2, 0x50, 0xb2, 0xf6, 0x0d, 0x25, 0x6b, 0xa3, 0x34, 0x4a, 0xfb,
	0x46, 0xa3, 0x74, 0xfe, 0x1d, 0x82, 0x7b, 0x0d, 0x11, 0xe2, 0xae, 0xfa, 0xe4, 0x2e, 0x6f, 0xb1,
	0x29, 0xf4, 0xb5, 0xa0, 0x30, 0x0b, 0x4c, 0xa1, 0xaf, 0x05, 0x6e, 0xe0, 0xca, 0x0d, 0x6f, 0xa4,
	0x18, 0xb8, 0xa4, 0x28, 0x8b, 0x8a, 0x94, 0xfd, 0x9f, 0xc4, 0xd2, 0x6a, 0x48, 0x30, 0x6f, 0xc5,
	0x9b, 0xac, 0xe4, 0x48, 0xb1, 0xb5, 0x3d, 0xc5, 0x7b, 0x88, 0xcd, 0x42, 0x9a, 0x65, 0x51, 0xb1,
	0xdc, 0xe3, 0xd6, 0xdd, 0x7d, 0x59, 0xcd, 0xac, 0x8f, 0x1b, 0x88, 0x78, 0x37, 0x50, 0x62, 0x63,
	0xd7, 0x3e, 0xf6, 0xfb, 0x37, 0x98, 0x71, 0xcd, 0x62, 0x3d, 0xf6, 0x9c, 0xe6, 0x76, 0x9e, 0xc5,
	0xf8, 0x00, 0x89, 0xd2, 0x95, 0xfe, 0x52, 0xb4, 0xc8, 0x82, 0x62, 0xb5, 0xbf, 0xf1, 0x5d, 0xf7,
	0x39, 0x5a, 0x93, 0xb9, 0x90, 0x3d, 0x50, 0x34, 0x94, 0x66, 0x41, 0x31, 0x63, 0x06, 0xe6, 0x77,
	0x90, 0x4c, 0x19, 0x5c, 0x40, 0xfc, 0x5c, 0xbe, 0x1c, 0xd6, 0xff, 0x0c, 0x7a, 0x3d, 0x1e, 0xca,
	0x75, 0x90, 0x3f, 0xc1, 0xd2, 0x9d, 0xdf, 0x0a, 0xa5, 0xb1, 0x80, 0xf9, 0x44, 0x15, 0x05, 0x76,
	0xea, 0xea, 0xef, 0x73, 0xcc, 0xdb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xc3, 0xa3, 0xbf,
	0xef, 0x01, 0x00, 0x00,
}
